version: '3.1'
services:
  app:
    container_name: StrapiAdmin
    restart: always
    build: .
    environment: 
      DB_HOST: db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      PORT: ${PORT}
    ports:
        - ${PORT}:${PORT}
    depends_on:
      - db
    links:
      - db:db

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: strapidb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: